name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
        # Server
      - name: install server dependencies
        working-directory: ./server
        run: npm install
      - name: lint server
        working-directory: ./server
        run: npm run eslint
      - name: server integration test
        working-directory: ./server
        run: CI=true npm test
        # Client
      - name: install client dependencies
        working-directory: ./client
        run: npm install
      - name: lint client
        working-directory: ./client
        run: npm run eslint
      - name: build client
        working-directory: ./client
        run: npm run build
      - name: Make .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_MONGODB_URI: ${{ secrets.MONGODB_URI }}
          envkey_TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          envkey_PORT: ${{ secrets.PORT }}
          envkey_SECRET: ${{ secrets.SECRET }}
      - name: e2e tests
        uses: cypress-io/github-action@v2.2.7
        with:
          working-directory: ./client
          command: npm run test:e2e
          start: npm run start:test-server
          wait-on: http://localhost:3000